"""One-off generator: compiles small Python snippets through
malbolge.compiler.py2c.compile_python_to_c and writes the resulting C sources
into test/fixtures/c2mg_corpus/from_py/. Not part of the test suite; kept
only as a record of how each fixture was produced (see manifest.json notes).
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", ".."))

from malbolge.compiler.py2c import compile_python_to_c

OUT = os.path.join(os.path.dirname(__file__), "from_py")
os.makedirs(OUT, exist_ok=True)

SAMPLES = {}

SAMPLES["func_return"] = '''
"""A function with a return value, called from top level."""
def addone(x):
    return x + 1

result = addone(41)
putchar(result)
'''

SAMPLES["fib_recursive"] = '''
"""Recursive fib, classic double-recursion form.
Per py2c design notes, this desugars to three-address CALLs
(t0 = fib(n-1); t1 = fib(n-2); r = t0 + t1) which sidesteps the upstream
highlevel double-CALL codegen bug -- so unlike a hand-written C
fib(n-1)+fib(n-2), THIS should compute correctly through the reference
compiler. We still include it because the recursive-call shape itself
(prototype, self-call) is worth conformance coverage."""
def fib(n):
    if n < 2:
        return n
    return fib(n - 1) + fib(n - 2)

putchar(fib(10))
'''

SAMPLES["while_loop"] = '''
"""Plain while loop counting up and emitting characters."""
i = 65
while i < 70:
    putchar(i)
    i += 1
'''

SAMPLES["for_range_simple"] = '''
"""for-i-in-range(n) loop; desugars to while in py2c."""
for i in range(5):
    putchar(65 + i)
'''

SAMPLES["for_range_start_stop_step"] = '''
"""for loop with explicit start/stop/step (step must be a positive literal)."""
total = 0
for i in range(2, 20, 3):
    total += i
putchar(total)
'''

SAMPLES["chained_compare"] = '''
"""Chained comparison a < b < c, materialized as nested ANDed comparisons."""
a = 3
b = 7
c = 20
if a < b < c:
    putchar(89)
else:
    putchar(78)
'''

SAMPLES["short_circuit_and"] = '''
"""Short-circuit 'and': second operand only evaluated if first is truthy.
Uses functions with putchar side effects so a byte diff against the
reference actually distinguishes short-circuit from eager evaluation."""
def left(v):
    putchar(76)
    return v

def right(v):
    putchar(82)
    return v

if left(0) and right(1):
    putchar(89)
else:
    putchar(78)

if left(1) and right(1):
    putchar(89)
else:
    putchar(78)
'''

SAMPLES["short_circuit_or"] = '''
"""Short-circuit 'or': second operand only evaluated if first is falsy."""
def left(v):
    putchar(76)
    return v

def right(v):
    putchar(82)
    return v

if left(1) or right(0):
    putchar(89)
else:
    putchar(78)

if left(0) or right(0):
    putchar(89)
else:
    putchar(78)
'''

SAMPLES["augmented_assign"] = '''
"""Exercise every augmented-assignment operator: += -= *= //= %=.
The *=, //=, %= forms are on variable operands (not both-literal), so per
_fold in py2c.py they are NOT constant-folded and route through the
injected zzmul/zzdiv/zzmod helpers."""
a = 10
b = 3
a += b
a -= 2
a *= b
a //= b
a %= 5
putchar(a)
'''

SAMPLES["zzmul_variable"] = '''
"""Multiplication of two non-constant operands: forces zzmul to be
emitted (constant folding only triggers when BOTH operands are literal
ints -- see _fold in py2c.py)."""
x = 6
y = 7
z = x * y
putchar(z)
'''

SAMPLES["zzdiv_variable"] = '''
"""Floor division of a variable by a variable: forces zzdiv."""
x = 100
y = 7
q = x // y
putchar(q)
'''

SAMPLES["zzmod_variable"] = '''
"""Modulo of a variable by a variable: forces zzmod."""
x = 100
y = 7
r = x % y
putchar(r)
'''

SAMPLES["global_and_multi_assign"] = '''
"""'global' declaration inside a function, plus chained multi-target
assignment (a = b = expr)."""
counter = 0

def bump():
    global counter
    counter = counter + 1
    return counter

bump()
bump()
p = q = bump()
putchar(p)
putchar(q)
'''

SAMPLES["getchar_echo_loop"] = '''
"""getchar()-driven loop: echoes characters until a sentinel is read.
Exercises getchar() plus a while loop with a compound condition."""
c = getchar()
while c != 0 and c != 10:
    putchar(c)
    c = getchar()
'''

SAMPLES["not_and_ord"] = '''
"""'not' operator plus ord() compile-time folding of a char literal."""
flag = 0
if not flag:
    putchar(ord('N'))
else:
    putchar(ord('Y'))
'''


def main():
    for name, src in SAMPLES.items():
        c_src = compile_python_to_c(src)
        # NB: the reference scanner's block-comment rule is `\/\*.*\*\/`,
        # which (flex `.` excludes newline) only matches within a single
        # line -- a multi-line /* */ header breaks parsing. Use one `//`
        # line comment per source line instead.
        header = "// Generated by py2c.compile_python_to_c from this Python source:\n"
        for line in src.strip("\n").splitlines():
            header += "// " + line + "\n"
        out_path = os.path.join(OUT, "py_{}.c".format(name))
        with open(out_path, "w") as f:
            f.write(header)
            f.write(c_src)
        print("wrote", out_path)


if __name__ == "__main__":
    main()
