// Generated by py2c.compile_python_to_c from this Python source:
// """Exercise every augmented-assignment operator: += -= *= //= %=.
// The *=, //=, %= forms are on variable operands (not both-literal), so per
// _fold in py2c.py they are NOT constant-folded and route through the
// injected zzmul/zzdiv/zzmod helpers."""
// a = 10
// b = 3
// a += b
// a -= 2
// a *= b
// a //= b
// a %= 5
// putchar(a)
int zzmul(int a, int b){
  int result; int rem; int cnt; int p; int ash; int j;
  result = 0; rem = b; cnt = 32;
  while(cnt != 0){
    cnt = cnt - 1;
    p = 1; ash = a; j = 0;
    while(j != cnt){ p = p + p; ash = ash + ash; j = j + 1; }
    if(rem >= p){ rem = rem - p; result = result + ash; }
  }
  return result;
}

int zzdiv(int a, int b){
  int q; int rem; int bsh; int p;
  q = 0; rem = a;
  if(b != 0){
    while(b <= rem){
      bsh = b; p = 1;
      while(bsh <= (rem - bsh)){ bsh = bsh + bsh; p = p + p; }
      rem = rem - bsh; q = q + p;
    }
  }
  return q;
}

int zzmod(int a, int b){
  int rem; int bsh;
  rem = a;
  if(b != 0){
    while(b <= rem){
      bsh = b;
      while(bsh <= (rem - bsh)){ bsh = bsh + bsh; }
      rem = rem - bsh;
    }
  }
  return rem;
}

int a;

int b;

int main(){
  a = 10;
  b = 3;
  a += b;
  a -= 2;
  a = zzmul(a, b);
  a = zzdiv(a, b);
  a = zzmod(a, 5);
  putchar(a);
}
