// Generated by py2c.compile_python_to_c from this Python source:
// """Chained comparison a < b < c, materialized as nested ANDed comparisons."""
// a = 3
// b = 7
// c = 20
// if a < b < c:
//     putchar(89)
// else:
//     putchar(78)
int a;

int b;

int c;

int main(){
  int zzt0;
  a = 3;
  b = 7;
  c = 20;
  zzt0 = 0;
  if(a < b){
    if(b < c){
      zzt0 = 1;
    }
  }
  if(zzt0 != 0){
    putchar(89);
  } else {
    putchar(78);
  }
}
