// Generated by py2c.compile_python_to_c from this Python source:
// """Recursive fib, classic double-recursion form.
// Per py2c design notes, this desugars to three-address CALLs
// (t0 = fib(n-1); t1 = fib(n-2); r = t0 + t1) which sidesteps the upstream
// highlevel double-CALL codegen bug -- so unlike a hand-written C
// fib(n-1)+fib(n-2), THIS should compute correctly through the reference
// compiler. We still include it because the recursive-call shape itself
// (prototype, self-call) is worth conformance coverage."""
// def fib(n):
//     if n < 2:
//         return n
//     return fib(n - 1) + fib(n - 2)
// 
// putchar(fib(10))
int fib(int n);

int fib(int n){
  int zzt0;
  int zzt1;
  int zzt2;
  int zzt3;
  int zzt4;
  int zzt5;
  zzt0 = 0;
  if(n < 2){
    zzt0 = 1;
  }
  if(zzt0 != 0){
    return n;
  }
  zzt1 = n - 1;
  zzt2 = fib(zzt1);
  zzt3 = n - 2;
  zzt4 = fib(zzt3);
  zzt5 = zzt2 + zzt4;
  return zzt5;
}

int main(){
  int zzt0;
  zzt0 = fib(10);
  putchar(zzt0);
}
