// Generated by py2c.compile_python_to_c from this Python source:
// """for loop with explicit start/stop/step (step must be a positive literal)."""
// total = 0
// for i in range(2, 20, 3):
//     total += i
// putchar(total)
int total;

int i;

int main(){
  int zzt0;
  total = 0;
  i = 2;
  zzt0 = 0;
  if(i < 20){
    zzt0 = 1;
  }
  while(zzt0 != 0){
    total += i;
    i += 3;
    zzt0 = 0;
    if(i < 20){
      zzt0 = 1;
    }
  }
  putchar(total);
}
