// Generated by py2c.compile_python_to_c from this Python source:
// """A function with a return value, called from top level."""
// def addone(x):
//     return x + 1
// 
// result = addone(41)
// putchar(result)
int addone(int x);

int result;

int addone(int x){
  int zzt0;
  zzt0 = x + 1;
  return zzt0;
}

int main(){
  int zzt0;
  zzt0 = addone(41);
  result = zzt0;
  putchar(result);
}
