// Generated by py2c.compile_python_to_c from this Python source:
// """for-i-in-range(n) loop; desugars to while in py2c."""
// for i in range(5):
//     putchar(65 + i)
int i;

int main(){
  int zzt0;
  int zzt1;
  i = 0;
  zzt0 = 0;
  if(i < 5){
    zzt0 = 1;
  }
  while(zzt0 != 0){
    zzt1 = 65 + i;
    putchar(zzt1);
    i += 1;
    zzt0 = 0;
    if(i < 5){
      zzt0 = 1;
    }
  }
}
