// Generated by py2c.compile_python_to_c from this Python source:
// """getchar()-driven loop: echoes characters until a sentinel is read.
// Exercises getchar() plus a while loop with a compound condition."""
// c = getchar()
// while c != 0 and c != 10:
//     putchar(c)
//     c = getchar()
int c;

int main(){
  int zzt0;
  int zzt1;
  int zzt2;
  int zzt3;
  int zzt4;
  int zzt5;
  int zzt6;
  zzt0 = getchar();
  c = zzt0;
  zzt1 = 0;
  zzt2 = 0;
  if(c != 0){
    zzt2 = 1;
  }
  if(zzt2 != 0){
    zzt3 = 0;
    if(c != 10){
      zzt3 = 1;
    }
    if(zzt3 != 0){
      zzt1 = 1;
    }
  }
  while(zzt1 != 0){
    putchar(c);
    zzt4 = getchar();
    c = zzt4;
    zzt1 = 0;
    zzt5 = 0;
    if(c != 0){
      zzt5 = 1;
    }
    if(zzt5 != 0){
      zzt6 = 0;
      if(c != 10){
        zzt6 = 1;
      }
      if(zzt6 != 0){
        zzt1 = 1;
      }
    }
  }
}
