// Generated by py2c.compile_python_to_c from this Python source:
// """'global' declaration inside a function, plus chained multi-target
// assignment (a = b = expr)."""
// counter = 0
// 
// def bump():
//     global counter
//     counter = counter + 1
//     return counter
// 
// bump()
// bump()
// p = q = bump()
// putchar(p)
// putchar(q)
int bump();

int counter;

int p;

int q;

int bump(){
  counter = counter + 1;
  return counter;
}

int main(){
  int zzt0;
  int zzt1;
  int zzt2;
  counter = 0;
  zzt0 = bump();
  zzt1 = bump();
  zzt2 = bump();
  p = zzt2;
  q = p;
  putchar(p);
  putchar(q);
}
