// Generated by py2c.compile_python_to_c from this Python source:
// """'not' operator plus ord() compile-time folding of a char literal."""
// flag = 0
// if not flag:
//     putchar(ord('N'))
// else:
//     putchar(ord('Y'))
int flag;

int main(){
  int zzt0;
  int zzt1;
  flag = 0;
  zzt1 = 0;
  if(flag != 0){
    zzt1 = 1;
  }
  zzt0 = 1;
  if(zzt1 != 0){
    zzt0 = 0;
  }
  if(zzt0 != 0){
    putchar(78);
  } else {
    putchar(89);
  }
}
