// Generated by py2c.compile_python_to_c from this Python source:
// """Short-circuit 'or': second operand only evaluated if first is falsy."""
// def left(v):
//     putchar(76)
//     return v
// 
// def right(v):
//     putchar(82)
//     return v
// 
// if left(1) or right(0):
//     putchar(89)
// else:
//     putchar(78)
// 
// if left(0) or right(0):
//     putchar(89)
// else:
//     putchar(78)
int left(int v);
int right(int v);

int left(int v){
  putchar(76);
  return v;
}

int right(int v){
  putchar(82);
  return v;
}

int main(){
  int zzt0;
  int zzt1;
  int zzt2;
  int zzt3;
  int zzt4;
  int zzt5;
  int zzt6;
  int zzt7;
  int zzt8;
  int zzt9;
  zzt0 = 0;
  zzt2 = left(1);
  zzt1 = 0;
  if(zzt2 != 0){
    zzt1 = 1;
  }
  if(zzt1 != 0){
    zzt0 = 1;
  } else {
    zzt4 = right(0);
    zzt3 = 0;
    if(zzt4 != 0){
      zzt3 = 1;
    }
    if(zzt3 != 0){
      zzt0 = 1;
    }
  }
  if(zzt0 != 0){
    putchar(89);
  } else {
    putchar(78);
  }
  zzt5 = 0;
  zzt7 = left(0);
  zzt6 = 0;
  if(zzt7 != 0){
    zzt6 = 1;
  }
  if(zzt6 != 0){
    zzt5 = 1;
  } else {
    zzt9 = right(0);
    zzt8 = 0;
    if(zzt9 != 0){
      zzt8 = 1;
    }
    if(zzt8 != 0){
      zzt5 = 1;
    }
  }
  if(zzt5 != 0){
    putchar(89);
  } else {
    putchar(78);
  }
}
