// Generated by py2c.compile_python_to_c from this Python source:
// """Plain while loop counting up and emitting characters."""
// i = 65
// while i < 70:
//     putchar(i)
//     i += 1
int i;

int main(){
  int zzt0;
  i = 65;
  zzt0 = 0;
  if(i < 70){
    zzt0 = 1;
  }
  while(zzt0 != 0){
    putchar(i);
    i += 1;
    zzt0 = 0;
    if(i < 70){
      zzt0 = 1;
    }
  }
}
