// Generated by py2c.compile_python_to_c from this Python source:
// """Modulo of a variable by a variable: forces zzmod."""
// x = 100
// y = 7
// r = x % y
// putchar(r)
int zzmod(int a, int b){
  int rem; int bsh;
  rem = a;
  if(b != 0){
    while(b <= rem){
      bsh = b;
      while(bsh <= (rem - bsh)){ bsh = bsh + bsh; }
      rem = rem - bsh;
    }
  }
  return rem;
}

int x;

int y;

int r;

int main(){
  x = 100;
  y = 7;
  r = zzmod(x, y);
  putchar(r);
}
