// Generated by py2c.compile_python_to_c from this Python source:
// """Multiplication of two non-constant operands: forces zzmul to be
// emitted (constant folding only triggers when BOTH operands are literal
// ints -- see _fold in py2c.py)."""
// x = 6
// y = 7
// z = x * y
// putchar(z)
int zzmul(int a, int b){
  int result; int rem; int cnt; int p; int ash; int j;
  result = 0; rem = b; cnt = 32;
  while(cnt != 0){
    cnt = cnt - 1;
    p = 1; ash = a; j = 0;
    while(j != cnt){ p = p + p; ash = ash + ash; j = j + 1; }
    if(rem >= p){ rem = rem - p; result = result + ash; }
  }
  return result;
}

int x;

int y;

int z;

int main(){
  x = 6;
  y = 7;
  z = zzmul(x, y);
  putchar(z);
}
