// Generated by py2c.compile_python_to_c from this Python source:
// """Floor division of a variable by a variable: forces zzdiv."""
// x = 100
// y = 7
// q = x // y
// putchar(q)
int zzdiv(int a, int b){
  int q; int rem; int bsh; int p;
  q = 0; rem = a;
  if(b != 0){
    while(b <= rem){
      bsh = b; p = 1;
      while(bsh <= (rem - bsh)){ bsh = bsh + bsh; p = p + p; }
      rem = rem - bsh; q = q + p;
    }
  }
  return q;
}

int x;

int y;

int q;

int main(){
  x = 100;
  y = 7;
  q = zzdiv(x, y);
  putchar(q);
}
